### ISSUE TITLE
get-lapsadpassword fails on LAPS4LINUX-rotated passwords

### ISSUE THREAD

**Issue by breakwaterlabs** [schorschii/LAPS4LINUX#34]
Out of the box, get-lapsadpassword will fail on accounts that have used LAPS4Linux, even though the AD 'LAPS' page in dsa.msc will succeed.

This is because LAPS4Linux outputs an incorrect header on the mslaps-encryptedPassword attribute.
    
While the Active Directory Users and Computers (dsa.msc) GUI does not seem to validate the filetime header, the powershell cmdlet parses the attribute to output information on the time the password was last set and runs into a type casting issue on the malformed header:

```
    Message        : Not a valid Win32 FileTime. (Parameter 'fileTime')
    ActualValue    :
    ParamName      : fileTime
    TargetSite     : System.DateTime FromFileTimeUtc(Int64)
    Data           : {}
    InnerException :
    HelpLink       :
    Source         : System.Private.CoreLib
    HResult        : -2146233086
    StackTrace     :    at System.DateTime.FromFileTimeUtc(Int64 fileTime)
                        at Microsoft.Windows.LAPS.EncryptedPasswordAttributePrefixInfo..ctor(UInt32 upperDateTimeStamp, UInt32 lowerDateTimeStamp, UInt32 encryptedBufferSize, UInt32 flagsReserved)
                        at Microsoft.Windows.LAPS.EncryptedPasswordAttributePrefixInfo.ParseFromBuffer(Byte[] buffer)
                        at Microsoft.Windows.LAPS.CmdletBase.ParseAndDecryptDirectoryPassword(IntPtr hDecryptionToken, Byte[] encryptedPasswordBytes, Boolean useRecoveryMode, Boolean useLocalKDS, DecryptionStatus& decryptionStatus)
                        at Microsoft.Windows.LAPS.GetLapsADPassword.BuildPasswordInfoFromEncryptedPassword(ComputerNameInfo computerNameInfo, PasswordSource passwordSource, Byte[] encryptedPassword, Nullable`1 passwordExpirationTimestampUTC, Boolean useRecoveryMode, Boolean
                    useLocalKDS)
                        at Microsoft.Windows.LAPS.GetLapsADPassword.ProcessOneIdentity(String Identity)
                        at Microsoft.Windows.LAPS.GetLapsADPassword.ProcessRecordInternal()
                        at Microsoft.Windows.LAPS.CmdletBase.ProcessRecord()
                        at System.Management.Automation.CommandProcessor.ProcessRecord()
```

This issue can be shown in powershell,  using DNSpy to debug lapspsh.dll (typically located at "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\LAPS\lapspsh.dll"), setting breakpoints at:

 * Microsoft.Windows.LAPS.GetLapsAdPassword, Line 44 (`PasswordInfo passwordInfo = this.BuildPasswordInfoFromEncryptedPassword(computerNameInfo, PasswordSource.EncryptedPassword, passwordAttributes.EncryptedPassword, passwordExpirationTimestampUTC, this.RecoveryMode, useLocalKDS);`)
 * Microsoft.Windows.LAPS.EncryptedPasswordAttributePrefixInfo, Line 25
 * Microsoft.Windows.LAPS.EncryptedPasswordAttributePrefixInfo, Line 41:  
            `long fileTime = (long)EncryptedPasswordAttributePrefixInfo.ConvertTwoUIntsToULong(upperDateTimeStamp, lowerDateTimeStamp)`

The last line is confusing because it actually matches what the LAPS4LINUX source code reports as the correct ordering-- upperDateTimeStamp, lowerDateTimeStamp-- but this is incorrect as according to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime) and [Raymond Chen](https://www.visualstudio-staging.com/oldnewthing/20040825-00/?p=38053):

```
typedef struct _FILETIME {
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
} FILETIME, *PFILETIME, *LPFILETIME;
```

It can also be experimentally proven that swapping this header byte order fixes things. Immediately prior to the exception, the two halves of the filetime can be seen in the locals window of dnSpy.
 * "Good" filetimes can be immediately decoded in powershell as `[datetime]::fromFileTimeUTC([long]0x<Upper><lower>)`.
 * "Bad" filetimes fail with a casting error, but can be decoded if their order is swapped.

This can be further proven out using powershell to test decoding, and upon failure rewriting the first 8 bytes by swapping the uint32s. See the first comment below for a script that does just that.

**Comment by breakwaterlabs** [comment]
This is a powershell script that performs a fixup.

```powershell
function fixup_laps {
	<#
    .SYNOPSIS
        Fixes up filetime header in msLAPS-EncryptedPassword attribute of computer objects by rotating 
        the order of upperDateTimeStamp and lowerDateTimeStamp
    .DESCRIPTION
        LAPS4LINUX takes a unix datetime and formats it as nanoseconds since epoch, formatted as a uint64. 
        However, Active Directory breaks that uint64 into 2 uint32s, re-ordered and packed as lowerDateTimeStamp, upperDateTimeStam.
        Because of this, when the Microsoft 'get-LAPSADPassword' cmdlet encounters a LAPS4LINUX msLAPS-EncryptedPassword, 
        it errors out on attempting to cast the invalid filetime as a datetime.
        This cmdlet attempts to run get-LAPSADPassword, and upon encountering a broken filetime header, will reorder 
        the first 8 bytes to the correct order. It will then offer to write-back the updated header to Active Directory.
    .NOTES
        Supports -verbose. Will prompt before writing changes to the directory.
    .EXAMPLE
        fixup_laps myComputer
        Fetches LAPS credential for myComputer. If invalid filetime encountered, offers to fix it.
    #>
    
    
	[CmdletBinding(
        SupportsShouldProcess=$true,
        ConfirmImpact= 'High'
        )]
    param (
        # Name of computer object to fetch from AD.
        [Parameter()]
        [string]
        $computerName
    )

	try {
		get-lapsadpassword $computername
        write-host "No fixup needed, filetime header is valid."
	} catch [System.ArgumentOutOfRangeException] {
        $_
        try {
            if ($_.exception.message -like "Not a valid Win32 FileTime. (Parameter 'fileTime')") {
                write-warning "Decoding failed due to bad 'filetime'. Rewriting header."
                $computer = get-adcomputer -identity $computerName -properties "operatingsystem",'msLaps-EncryptedPassword'
                $filePath = ".\laps_fixup_$computername.clixml"
                $computer | export-clixml -path $filePath
                Write-host "Saved prior state of $computer object to $filePath"
                $msLapsPwd = $computer.'msLaps-EncryptedPassword'
                $msLapsPwdNew = [byte[]]::new($msLapsPwd.length)
                $hexFileTime = [System.Text.StringBuilder]::new('0x')
                $hexFileTimeNew = [System.Text.StringBuilder]::new('0x')
                for ($i = 0; $i -lt $msLapsPwd.length; $i++) {
                    if ($i -lt 8) {
                        if ($i -lt 4) {
                            $newPos = $i+4
                        } else {
                            $newPos = $i-4
                        }
                        $byte = $msLapsPwd[$i]
                        $hex = $byte.toString('X2')
                        write-verbose "Position $i -  byte $byte ($hex) moved to position $newPos"
                        $msLapsPwdNew[$newPos] = $byte
                        [void]$hexFileTime.append($hex)
                        [void]$hexFileTimeNew.append($msLapsPwd[$newPos].toString('X2'))
                    } else {
                        $msLapsPwdNew[$i] = $msLapsPwd[$i]
                    }
                }
                Write-host "Changed filetime header of msLAPS-EncryptedPassword from  $($hexFileTime.toString()) --> $($hexFileTimeNew.toString())."
                if ($psCmdlet.shouldProcess($computerName, "Write updated msLAPS-EncryptedPassword back to directory")) {
                    $computer | set-adobject -Replace @{"mslaps-encryptedpassword"=$msLapsPwdNew} -verbose
                    write-host "Sleeping for 5 seconds..."
                    start-sleep 5
                    get-lapsadpassword $computerName
                }
            }
        } catch {
            $_
        }
	}catch {
		$_
	}
}
```

**Comment by breakwaterlabs** [comment]
I've opened pull request #35 which results in fixed msLAPS-EncryptedPassword attributes that can be retrieved by both the `dsa.msc` GUI, and the powershell `get-lapsadpassword` cmdlets.

**Comment by schorschii** [comment]
Thanks @breakwaterlabs ! This is impressive reverse engineering. I have to admit that I only tested it with the GUI and not with the Powershell cmdlet.

Also, huge thanks for the fixup script and pull request with the ready-to-use  solution!
